<?php
include_once"settings/settings.php";
include_once"classes/userclass.php";
$obj=new userclass();
session_start();
if(isset($_COOKIE['logined'])&&$_COOKIE['logined']==1)
{
$key=$_COOKIE['lkey'];
$r=$obj->repnot($key);
$smartyObj->assign("views",$r);
//$smartyObj->display('studsubheader.tpl');
$smartyObj->display('studhome.tpl');
//$smartyObj->display('footer.tpl');
}
else
{
	Header("location:login.php");
}
?>